### ISSUE TITLE
Pillar Pages - Brotherhood, Service & Professionalism

### ISSUE THREAD

**Issue by roenw** [roenw/ThetaTau-Website#11]
Will have to decide if we would like one page for all the pillars (similar to Berkely's page: https://www.calthetatau.com/about) or if we want Professionalism, Brotherhood, and Service broken out.

**Comment by roenw** [comment]
Going to combine all the pillars, possibly have about combined as well but may also stay separate.

**Comment by tssanjai98** [comment]
Did the initial commit for the pillars page with a simple design.

Pending tasks:
1. Need to work on the page responsiveness.
2. Need to change the text for the pillars and any changes in the images if required.

**Comment by tssanjai98** [comment]
Done with final design for the Pillars page. 
The code still needs refactoring and also the website responsiveness needs to be fixed.
